name: flutter_swish_payment
description: A Swish commerce widget library for Flutter.
version: 0.0.1-alpha
homepage: https://github.com/johanehinger/flutter_swish_payment

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - images/
